FROM base:0.1

RUN apt update && apt upgrade

RUN apt install build-essential gdb cmake -y

RUN apt install python3 python3-pip -y \
    && pip install numpy pandas matplotlib

RUN apt install nodejs npm -y

RUN apt install golang -y

RUN apt install openjdk-8-jdk -y

